### ISSUE TITLE
Fragment identifier lost

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/webauthn#13]
The fragment identifier of the URL is getting lost sometime in the login process. Serban has looked at it and confirmed to his knowledge that the referrer is passed correctly during the process. The easiest way to see the bug is following the link entered by Carl in the associated Chaise issue. At this point it looks like it needs tracing at the webauthn level.

Related issue:
https://github.com/informatics-isi-edu/chaise/issues/190

(I hope I've translated this issue correctly...)

This is a fairly critical issue -- but not more critical than the globus id migration of course.

**Comment by karlcz** [comment]
Can a reproducible test case be created that works on dev.misd so no interaction with the GPCR server or restricted groups is required?

**Comment by carlkesselman** [comment]
Not by me…..

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Feb 9, 2016, at 5:11 PM, karlcz <notifications@github.com<mailto:notifications@github.com>> wrote:

Can a reproducible test case be created that works on dev.misd so no interaction with the GPCR server or restricted groups is required?

**Comment by bugacov** [comment]
I assume we can rollout the gpcr-www repo to have a landing page and adjust
the bookmarks if needed?
Alejandro.

**Comment by karlcz** [comment]
This bug is in Chaise, not webauthn. Fix will be pushed to chaise momentarily.

**Comment by bugacov** [comment]
This is now rolled out in gpcr-dev and works well!!!
Alejandro.
