### ISSUE TITLE
Webauthn support for Apache static pages

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#14]
For some use cases, it seems we'd want to have some kind of `mod_webauthn` module for Apache to allow webauthn-based access control policies on static pages etc.  Currently, we can only apply such policies in our own custom Python web services.
1. Provide equivalent to the Python-based get-message-context operation that we perform at the top of each of our web service request handlers. This could literally use the webauthn codebase via `mod_python` or perhaps just reimplement a thin shim layer that assumes our cookie-based session security. We should configure this via Apache config directives, and not expect it to read the webauthn service configuration file. The configuration should just be the base URL of the `/authn` API where we can make REST calls from the module using the client credentials.
2. Document how this new feature can be used with normal Apache security directives to prevent unauthorized access to pages.
   - Kick anonymous users out to login and back to the requested page on success
   - Serve a forbidden error for authenticated users who lack privilege to view the page
3. Add session context to an Apache environment variable or similar so that this module can be composed with our mod_wsgi services and they can view the current webauthn context without having to know anything about the webauthn service configuration.
4. Add suitable default apache config and test cases for generic use and travis builds
   - Configure all directives to default values as self-documenting example
   - Add a deploy-tests make target to create additional Apache conf files and invoke this from travis build
     - Use static files and/or CGI test endpoint
     - Use multiple locations to exercise different `Require` scenarios
     - Look at existing makefile hacks for portability between centos and ubuntu (httpd vs apache2 dir names)
   - Add a client-side test script and invoke from travis build
     - Exercise scenarios of anonymous access, unauthorized, forbidden, authorized by username, authorized by group
     - Check that session extension is happening due to access to module-protected locations

**Comment by karlcz** [comment]
I added a third point to this issue description based on a conversation I had with @ljpearlman to refactor our handling of basic message authentication in services.

**Comment by karlcz** [comment]
I've tested this in combination with Hatrac (not static files).  Current gotchas:

1. The default WebauthnCookieName directive is `ermrest` while webauthn/master defaults to `webauthn` as the session cookie name.
2. It doesn't seem like the module is making PUT session requests, so a series of resource access requests that are guarded by the module will not extend session lifetime and it will suddenly timeout when you expect things to stay alive (assuming you've made no other webauthn-related requests as a client yourself).

**Comment by karlcz** [comment]
I have been thinking about this, and I think the module should *always* use PUT rather than GET on sessions.  Since there is a caching layer that throttles request rates, I don't think there is any value in further trying to limit the session extension requests from the module's perspective.

**Comment by karlcz** [comment]
I added a fourth issue description clause about config and test case integration needed to call this work complete.

**Comment by ljpearlman** [comment]
At this point I think this is basically done except for the test cases. The documentation is more complete, too.

**Comment by karlcz** [comment]
I added a small static file test suite and fiddled until I got it to work on travis (confusing due to self-signed cert, old apache, and old libcurl).  In the process what I thought would be one simple commit turned into a mess that probably should have been in a pull request...

So, @ljpearlman please review [the aggregate changes](https://github.com/informatics-isi-edu/webauthn/compare/7c30a5419a593fbd8c9e04ac1a9918a47cb8e022...master) for sanity.

I had to modify mod_webauthn to also set CURLOPT_SSL_VERIFYPEER to `0L` when we turn off CURLOPT_SSL_VERIFYHOST via directives.  This, combined with setting the `ServerName` directive finally got the test suite to pass on the travisci ubuntu VM.

I used the documentation to figure out how to write this test suite and to debug stuff, so I consider this issue complete and ready to close if you review the changes above and consider them to be OK.
