### ISSUE TITLE
Incorrect padding cookie error in new privisioned VM (gpcr-staging.misd.isi.edu)

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/webauthn#17]
In this VM when trying to authenticate the server throws an "Incorrect padding" error. 
The server whitelisting seems to be ok because I do get authenticated. I compared the cookies file I get using the dev machine and they seem to look very similar. 
Below is the trace stack and cookies. 

[Mon Feb 22 10:19:42.383890 2016] [:error] [pid 3849] [remote 128.9.136.65:116] "in GET /preauth, user agent is 'ERMREST/1.0'"
[Mon Feb 22 10:19:42.384173 2016] [:error] [pid 3849] [remote 128.9.136.65:116] "in GET /preauth, referrer arg is 'https://gpcr-staging.misd.isi.edu/chaise/search/#1/gpcr_browser:construct_gui?facets=(construct_gui:site::eq::USC)&layout=table&page=1', Referrer header is 'https://gpcr-staging.misd.isi.edu/chaise/search/'"
[Mon Feb 22 10:19:42.387440 2016] [:error] [pid 3849] [remote 128.9.136.65:116] 'in generate_nonce, referrer arg is https://gpcr-staging.misd.isi.edu/chaise/search/#1/gpcr_browser:construct_gui?facets=(construct_gui:site::eq::USC)&layout=table&page=1, generated nonce is 1456165182.Etb525c4GSaHE3S7Q4aiLsUg5VdXJvcaZSx_MVAc.aHR0cHM6Ly9ncGNyLXN0YWdpbmcubWlzZC5pc2kuZWR1L2NoYWlzZS9zZWFyY2gvIzEvZ3Bjcl9icm93c2VyOmNvbnN0cnVjdF9ndWk_ZmFjZXRzPShjb25zdHJ1Y3RfZ3VpOnNpdGU6OmVxOjpVU0MpJmxheW91dD10YWJsZSZwYWdlPTE='
[Mon Feb 22 10:19:43.280461 2016] [:error] [pid 3852] [remote 128.9.136.65:112] "in GET /session, referrer arg is 'None', Referrer header is 'https://gpcr-staging.misd.isi.edu/chaise/search/'"
[Mon Feb 22 10:19:52.596793 2016] [:error] [pid 3851] [remote 128.9.136.65:112] "in GET /session, referrer arg is 'None', Referrer header is 'https://www.globusid.org/oauth?client_id=auth&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fp%2Fauthenticate%2Fcallback&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Byb3ZpZGVyX2lkIjoiNTAwNiIsInJmcCI6Ino1Y09BZ3REV3J1YzJWSWRTUFQ4X0JSLSIsImZsb3ciOiJsb2dpbiIsImNvbnRpbnVlX3RvIjpbIi92Mi9vYXV0aDIvYXV0aG9yaXplP3N0YXRlPTNkYmMzMGM2MzlmMjRiMDdkY2IwMTRhMDhhYjY2M2M4NTkxNjljMzY2NmZmMTM0M2JiNDlmZTgxYTE0ZDg3NzkmcmVkaXJlY3RfdXJpPWh0dHBzJTNBJTJGJTJGZ3Bjci1zdGFnaW5nLm1pc2QuaXNpLmVkdSUyRmVybXJlc3QlMkZhdXRobiUyRnNlc3Npb24mcmVzcG9uc2VfdHlwZT1jb2RlJmNsaWVudF9pZD0zODJmODQ2Ni1jMTVhLTExZTUtYjdlMC0zYzk3MGUwYzljYzQiXSwiZXhwIjoxNDU2MTY1NzgzfQ.Y6IbW3PuwwjbviOEkuC82ScMwa-ZYSCJ4OLGFHDG6Bk'"
[Mon Feb 22 10:19:53.432998 2016] [:error] [pid 3851] [remote 128.9.136.65:112] 'passing https://gpcr-staging.misd.isi.edu/ermrest/authn/session as referrer_uri'
[Mon Feb 22 10:19:53.914906 2016] [:error] [pid 3851] [remote 128.9.136.65:112] "Globus access token: 'un=bugacov|tokenid=dea07974-d990-11e5-bf80-22000ab4b42b|expiry=1487701193|client_id=bugacov|token_type=Bearer|SigningSubject=https://nexus.api.globusonline.org/goauth/keys/a2c05f56-d732-11e5-88b9-22000aef184d|sig=07b25d4fb6330c3a771b87b80d6854a41f956d260520c965e5857066dee50a92cd197b23d8709b649e0530cd344d2bd288e09a1284c81c3632851464387fc3ccecca57b00030724d762b951a8409102e292b646c93c3dd6abd539964d7f7b0e2d46d4d5d7fcdf045800ea94fe26585de5f29e504c3164dccccb5a3bda45dafef'"
[Mon Feb 22 10:19:55.584840 2016] [:error] [pid 3851] [remote 128.9.136.65:112] Traceback (most recent call last):
[Mon Feb 22 10:19:55.584867 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/web/application.py", line 239, in process
[Mon Feb 22 10:19:55.584870 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     return self.handle()
[Mon Feb 22 10:19:55.584872 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/web/application.py", line 230, in handle
[Mon Feb 22 10:19:55.584875 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     return self._delegate(fn, self.fvars, args)
[Mon Feb 22 10:19:55.584877 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/web/application.py", line 405, in _delegate
[Mon Feb 22 10:19:55.584879 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     return handle_class(f)
[Mon Feb 22 10:19:55.584881 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/web/application.py", line 396, in handle_class
[Mon Feb 22 10:19:55.584884 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     return tocall(*args)
[Mon Feb 22 10:19:55.584886 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/webauthn2/rest.py", line 243, in GET
[Mon Feb 22 10:19:55.584888 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     return self._login_get_or_post(web.input())
[Mon Feb 22 10:19:55.584899 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/webauthn2/rest.py", line 360, in _login_get_or_post
[Mon Feb 22 10:19:55.584902 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     preauth_referrer = self.manager.preauth.preauth_referrer()
[Mon Feb 22 10:19:55.584905 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/webauthn2/providers/oauth2.py", line 472, in preauth_referrer
[Mon Feb 22 10:19:55.584907 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     return nonce_util.get_cookie_url(web.cookies().get(self.nonce_cookie_name))
[Mon Feb 22 10:19:55.584909 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib/python2.7/site-packages/webauthn2/providers/oauth2.py", line 148, in get_cookie_url
[Mon Feb 22 10:19:55.584911 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     url = base64.b64decode(cookie.split('.')[2])
[Mon Feb 22 10:19:55.584913 2016] [:error] [pid 3851] [remote 128.9.136.65:112]   File "/usr/lib64/python2.7/base64.py", line 76, in b64decode
[Mon Feb 22 10:19:55.584915 2016] [:error] [pid 3851] [remote 128.9.136.65:112]     raise TypeError(msg)
[Mon Feb 22 10:19:55.584917 2016] [:error] [pid 3851] [remote 128.9.136.65:112] TypeError: Incorrect padding
[Mon Feb 22 10:19:55.584925 2016] [:error] [pid 3851] [remote 128.9.136.65:112] 
[Mon Feb 22 10:20:09.338609 2016] [:error] [pid 3851] [remote 128.9.136.65:32369] "in GET /session, referrer arg is 'None', Referrer header is 'https://gpcr-staging.misd.isi.edu/chaise/search/'"

==================================

ermrest=> select * from webauthn2_goauth.session;
           key            | key_old |            since             |           keysince           |            expires            | client  |          
                                                                attributes                                                                           
--------------------------+---------+------------------------------+------------------------------+-------------------------------+---------+----------
-----------------------------------------------------------------------------------------------------------------------------------------------------
 ggmM2pcsnphJQIEOkOSuztBJ |         | 2016-02-22 10:19:55.57705-08 | 2016-02-22 10:19:55.57705-08 | 2016-02-22 10:50:09.251016-08 | bugacov | {g:3dafcd
ea-fbfa-11e4-86df-22000aa51e6e,g:6489c7d4-b5bf-11e5-b1f4-22000aef184d,g:f69e0a7a-99c6-11e3-95f6-12313809f035,g:143f5bdc-c127-11e4-ab32-22000a1dd033}
(1 row)

===========================

# Netscape HTTP Cookie File
# http://www.netscape.com/newsref/std/cookie_spec.html
# This is a generated file!  Do not edit.

auth.globus.org FALSE   /       TRUE    1458757191      auth_tkt        4440cf84ba792e7e1c8e3f238a38689f97139d5d63644783dd276af99ea7617b8a5e7ffe33ae5c302b70e66c04885bad1ac8101a58d47e6b88c3af394b2c35aa56cb5147YjUwNjk2M2UtZDI3NC0xMWU1LTk5ZjAtNjdlZTczZGQ0YzNm!userid_type:b64str
.auth.globus.org        TRUE    /       TRUE    1458757191      auth_tkt        4440cf84ba792e7e1c8e3f238a38689f97139d5d63644783dd276af99ea7617b8a5e7ffe33ae5c302b70e66c04885bad1ac8101a58d47e6b88c3af394b2c35aa56cb5147YjUwNjk2M2UtZDI3NC0xMWU1LTk5ZjAtNjdlZTczZGQ0YzNm!userid_type:b64str
auth.globus.org FALSE   /       TRUE    0       session cd5443b8726e328899932f8b98654a52df40ec60CdzIcNHX92CQqi4ZLm/csg==WEQMb0Tusj2E58ki0Fz5MmsBoDC55+Y8LglnpuM5Rf9Ka/OMOdlQPvQ46mLcB+/CKvowbPX/gXE4lh86sdIDxHSZx+gxJh75KB3OiK2AhiZi3komnX63mA5epTxta8nxzClA6MP3fckM
gpcr-staging.misd.isi.edu       FALSE   /ermrest/       TRUE    0       oauth2_auth_nonce       1456165182.Etb525c4GSaHE3S7Q4aiLsUg5VdXJvcaZSx_MVAc.aHR0cHM6Ly9ncGNyLXN0YWdpbmcubWlzZC5pc2kuZWR1L2NoYWlzZS9zZWFyY2gvIzEvZ3Bjcl9icm93c2VyOmNvbnN0cnVjdF9ndWk_ZmFjZXRzPShjb25zdHJ1Y3RfZ3VpOnNpdGU6OmVxOjpVU0MpJmxheW91dD10YWJsZSZwYWdlPTE%3D
gpcr-staging.misd.isi.edu       FALSE   /       TRUE    0       ermrest ggmM2pcsnphJQIEOkOSuztBJ
~

**Comment by karlcz** [comment]
With further testing it seems this failure is specific to this referrer argument `https://gpcr-staging.misd.isi.edu/chaise/search/#1/gpcr_browser:construct_gui?facets=(construct_gui:site::eq::USC)&layout=table&page=1` and does not occur for a simpler argument like `https://gpcr-staging.misd.isi.edu/chaise/search`, so there seems to be a hole in the URL parsing and/or encoding in the goauth provider.

**Comment by bugacov** [comment]
I think this is confirmed now.
From the landing page https://gpcr-staging.misd.isi.edu/data/ the biomass
links seem to work ok but the
Target and construct links produce the server error.

The same error doesn't happen when using the landing site
https://gpcr-dev.misd.isi.edu/data/

**Comment by ljpearlman** [comment]
Must be the # character, thanks.

               -- Laura

**Comment by karlcz** [comment]
I think this is fixed in 87279aafd9822f3a6066c58760bf7c0e09e8f9bc so please update your webauthn library, restart httpd, and give it a test.

**Comment by bugacov** [comment]
I don't think the # sign must be the problem cos the issue seems to be more dependent on the url prefix (i.e., the server name part of the url) than in the rest of the link. To give you an example:

dev.gpcrconsortium.org is an alias for gpcr-dev.misd.isi.edu

The links for Constructs -> USC work well if coming from gpcr-dev.misd.isi.edu but breaks if getting to the same page from its alias dev.gpcrconsortium.org

The inverse happens with staging.gpcrconsortium.org and gpcr-staging.misd.isi.edu

The static landing pages with the bookmarks contain only the relative url

**Comment by bugacov** [comment]
that seems to have fixed it!!
