### ISSUE TITLE
The authentication workflow force new users to link to an existing globus account

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/webauthn#18]
It seems like the action of the "Do Not link to globus account" is pointed to the wrong code..

* I just tried logging in using my usc/google account to staging.gpcrconsortium.org.

* The first time I went through the process, there was a step that asked me whether I wanted to link to the existing account, or not. In this case, I chose not. 
![link_to_globus_account](https://cloud.githubusercontent.com/assets/414732/13334058/d7c5e884-dbbe-11e5-8d97-ced1645611df.png)

* Then it lead me to the page that asked to link to the globus account (despite the fact that I said no)
![link_an_identity](https://cloud.githubusercontent.com/assets/414732/13334070/e8eed24c-dbbe-11e5-9965-e5f293b713bd.png)

* I cleared all my cookies..

* Then I tried to go through the same process again.. This time, it always assume that I want to link to my globus accounts and therefore lead me to link my identity over again. 

* Despite all the awkward flow, I got an invitation to add myself to the group. So when I logged in to globus using my usc identity, I was able to add myself into the group.

**Comment by hongsudt** [comment]
To summary the issue based on our email thread with Kyle, 
* With legacy GOAuth support you have to link to a Globus identity as that is the only way GOAuth can work.
* With the new Globus Auth model you will not need to link to a Globus identity.

We decided based on the call on 02/26 that: 
* The temporary solution is to use only globus ID to avoid the confusion of account linkage. 
* Long term solution: test and deploy our web authen using the new Globus Auth model (#12). 

Will test this on Tues after Kyle update the whitelist to use Legacy Auth (except dev.isrd.isi.edu, webauthen-dev.isrd.isi.edu)

**Comment by carlkesselman** [comment]
This is consistent with my understanding of the situation.

My recommendation is that we move forward rapidly with the new Globus Auth model, as I think that this will minimize user confusion even in the short run.

By “this” in the last sentence, you mean webauth with the new authentication model.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Feb 26, 2016, at 2:51 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


To summary the issue based on our email thread with Kyle,

  *   With legacy GOAuth support you have to link to a Globus identity as that is the only way GOAuth can work.
  *   With the new Globus Auth model you will not need to link to a Globus identity.

We decided based on the call on 02/26 that:

  *   The temporary solution is to use only globus ID to avoid the confusion of account linkage.
  *   Long term solution: test and deploy our web authen using the new Globus Auth model (#12<https://github.com/informatics-isi-edu/webauthn/issues/12>).

Will test this on Tues after Kyle update the whitelist to use Legacy Auth (except dev.isrd.isi.edu<http://dev.isrd.isi.edu>, webauthen-dev.isrd.isi.edu<http://webauthen-dev.isrd.isi.edu>)

**Comment by hongsudt** [comment]
Sorry for the vague use of the word long term. The Globus Auth model will be in the next sprint expecting to have it tested and ready by end of 2016-03 cycle. We already set up a meeting on 03/02 when Kyle is in the area to go over the technical solution/expectation.

**Comment by carlkesselman** [comment]
Excellent.  I think that should be fine and kind of what I was hoping for.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Feb 26, 2016, at 3:06 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the vague use of the word long term. The Globus Auth model will be in the next sprint expecting to have it tested and ready by end of 2016-03 cycle. We already set up a meeting on 03/02 when Kyle is in the area to go over the technical solution/expectation.

**Comment by ljpearlman** [comment]
There doesn't appear to be a DNS entry for dev.isrd.isi.edu yet. Is anyone working on changing that host's name? I was hoping to test the new stuff on that host (which needs the name change because of the white list entry) next week.

**Comment by crisaless** [comment]
if you can get me the hostname - and maybe IP address to be safe - I can ask Action for the DNS entry.

**Comment by karlcz** [comment]
I don't think anyone has requested it yet.  I think this request is
supposed to go through colo-mgmt.  I believe we have the *.isrd cert
ready and waiting.

If they could add the new name as an A record to the existing IP and
drop the old A record later when we are ready, that would be ideal to
minimize disruption...

**Comment by ljpearlman** [comment]
@crisaless Thanks! dev.isrd.isi.edu 128.9.128.88. And dev.misd.isi.edu should be changed into a CNAME record (alias) that points to dev.isrd.isi.edu.

**Comment by crisaless** [comment]
fyi, Ken from Action replied with this - which relates to how the IP address is actually assigned. Sounds like we want the second option:

"Currently, 128.9.128.88 is assigned to dev.misd.isi.edu. Do you want us to add a CNAME dev.isrd.isi.edu to point to dev.misd.isi.edu or do you want us to assign IP address 128.9.128.88 to dev.isrd.isi.edu and remove dev.misd.isi.edu?"

**Comment by karlcz** [comment]
We are trying to migrate from the old MISD name to the new ISRD name.  As Laura said in a previous comment, we want the new dev.isrd.isi.edu name to point to the existing IP address.  We'd like to keep the old name as a CNAME for a few weeks to help us transition existing clients off to the new name, then we can drop the old MISD name for this host permanently.

**Comment by hongsudt** [comment]
Staging.gpcr* is now using the right login flow. Will close this issue.
