### ISSUE TITLE
ETL Script to upgrade webauthn DB

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/webauthn#19]

**Comment by karlcz** [comment]
I suspect this is supposed to be project-specific ETL to fixup ERMrest databases that contain raw webauthn user IDs to instead contain the new denormalized user references we plan for this release.  I think other staff would do that ETL, but @ljpearlman would help provide the core mapping table needed to convert the old ID to the new format.

**Comment by ljpearlman** [comment]
We've split that out into a different issue. This one is the database 
used internally by webauthn itself.

                   -- Laura

**Comment by karlcz** [comment]
Does this issue include getting a master mapping table of usernames and groupnames to the new representation?  Or is that another issue we still need to create?

**Comment by hongsudt** [comment]
@ljpearlman is this issue done? I am moving it to 2016-04 milestone. Please put it under review or close it if it is done.

**Comment by karlcz** [comment]
Sorry I'm not clear on what I am supposed to review here. Can you point me to some code or a revision or something?

**Comment by ljpearlman** [comment]
It's the stuff in https://github.com/informatics-isi-edu/webauthn/tree/globus_auth/webauthn2/scripts/globus_auth_upgrade (minus the script that you wrote).

**Comment by karlcz** [comment]
I understand this upgrade as an optional step to carry forward existing user information collected from past visits. Otherwise, the new system will start over with an empty user table and only collect user info for future visits.

**Comment by ljpearlman** [comment]
Just realized we need one of these for the database provider.

**Comment by karlcz** [comment]
Unless Mike needs it, I don't think it matters.  We mostly use the database provider in transient deployments that would have no need to upgrade.

**Comment by ljpearlman** [comment]
There's now a script that will find the schema names in the ermrest and hatrac config files and upgrade schemas in place. I've also bumped the db version numbers so the script can see whether it's been run more than once. In https://github.com/informatics-isi-edu/webauthn/tree/globus_auth/webauthn2/scripts/v2_upgrade

**Comment by karlcz** [comment]
I don't have any plans to run this upgrade script so am reassigning to @bugacov to review when he applies these changes to his next dev VM

**Comment by ljpearlman** [comment]
@bugacov - you can run /usr/sbin/webauthn2-v2-upgrade as root instead of dropping database schemas and running ermrest-webauthn2-deploy. This will update both the ermrest and hatrac databases. If you're not using hatrac, you can use the --ermrest-only option to just update the ermrest db.

(By default, the script tries to update the hatrac db only if ~hatrac/webauthn_config.json exists. But if the config file exists and the hatrac database doesn't, you'll get an error message).

**Comment by karlcz** [comment]
We just tested this on gpcr-dev to upgrade to the globus_auth branch while remaining on the goauth provider config.  Some minor bugs were found and a patch committed.  I think we can call this complete.
