### ISSUE TITLE
Create recipe for webauthn-dev based on dev.isrd, with globus_auth authentication

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/webauthn#21]
This is what we talked about as part of the current sprint; we just neglected to make an issue for it.

**Comment by karlcz** [comment]
@ljpearlman did you assign me the wrong issue?  I said I'd work on isrd-dev, not on your webauthn-dev vm...?

**Comment by ljpearlman** [comment]
Oops -- yeah, sorry.

**Comment by karlcz** [comment]
The synapse-dev and isrd-dev recipes should be good examples for this now...

**Comment by ljpearlman** [comment]
Thanks! I actually completed this with commit 8f69e9756e98ee5417987ee92da3c6efb4523aab, although I didn't realize it at the time (I thought there was some magic I was missing to use a branch).

**Comment by karlcz** [comment]
You might want to compare your recipe to synapse-dev... I refactored a bunch of ISRD standard stuff into a common Makefile to reduce the repetition and divergence of different VM recipes.  I think eventually that most recipes will converge to use this style, so we can update in one place to apply a fix to our standard methods...
