### ISSUE TITLE
Deprecate crowd-based and oauth1a providers

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/webauthn#22]
We need to either get rid of or support (provide documentation and tests for) these providers: crowd2, crowdrest1, and oauth1a.

**Comment by karlcz** [comment]
I think we should drop the crowd providers as we are not maintaining nor testing them.

**Comment by karlcz** [comment]
crowd providers pruned out in 15ed2d679ad9fa545970cef7538f6a65ffdb25e3

**Comment by hongsudt** [comment]
@ljpearlman I am putting this in review. Please close the issue if it is done.
