### ISSUE TITLE
Deprecate globusonline and goauth providers

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#25]
We expect globus-based deployments to switch to the new globus_auth provider that speaks to their current generation protocols. Let's deprecate and then remove the old globusonline and goauth providers in webauthn since they will not be getting maintenance and test attention.

**Comment by karlcz** [comment]
This is done in the restapi branch.  So, when we merge that we cannot support legacy servers anymore...

**Comment by ljpearlman** [comment]
Is there a reason this needs to be done in the restapi branch? This may mean a significant delay in merging that branch, and I thought we were trying to move away from that.

**Comment by karlcz** [comment]
We won't delay the merge for the sake of legacy provider consumers.
Since this branch is already disrupting deployment and build processes
(again) I don't want to have any more intermediate deployment
milestones.  Any deployment not yet on the providers we will support
in the future MUST migrate first (or stay on their previous revision
until they can do so).

The only thing I'd consider delaying this branch is a decision on how
to handle the new mod_webauthn integration.  It makes sense to me that
we could handle it all at once...

**Comment by karlcz** [comment]
Can you review that I've removed the modules and associated documentation w/o breaking the remaining ones?

**Comment by ljpearlman** [comment]
Looks good to me; I removed one more file that appears to be used only by the globusonline provider. Bouncing it back to @karlcz for review because I touched it last.

**Comment by karlcz** [comment]
Looks good to me.
