### ISSUE TITLE
Add required_attributes ACL

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#26]
As we migrate to identity and attribute providers with more global scope, it is not very meaningful to merely require an identity.  We may want to require membership in a certain group as a basic gateway to start a webauthn session on a particular deployed server.

**Comment by ljpearlman** [comment]
I agree that just requiring an identity isn't a good mechanism for access control. This seems like something that should be done at the container layer, implemented with mod_webauthn (#14) and httpd config directives.

**Comment by ljpearlman** [comment]
I don't think this belongs in the "migration to globus auth" epic. It's new functionality orthogonal to the choice of provider, and it's not a prerequisite for using globus_auth for authentication.

**Comment by karlcz** [comment]
Hmm, I think the required_attributes ACL would restrict login, not resource access subsequent to login.  It is not a job for mod_webauthn which is analogous to the resource-level ACLs in our other services.  Instead, it is a decision whether authentication and session establishment is allowed to complete at all.

Even if there is little or no difference in resource consumption on the back-end, I think the UX is quite different to say "you've logged in, but are forbidden to access anything" and "you failed to login with an identity recognized by this system".

So, I could imagine implementing it in the generic manager layer in webauthn for now, though it would be nice to delegate it further down into the providers if they can do a more efficient job of enforcing it (with lower denial of service risks, etc.)

**Comment by karlcz** [comment]
I guess I'm going to agree for expedience that we can require group membership via mod_webauthn and it's going to take later pondering and work to do anything better about rejecting logins.  That seems inherently identity-provider specific...
