### ISSUE TITLE
Save user last access information

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/webauthn#27]
We need this information so that we can remove users that haven't been active for a certain period of time.

**Comment by ljpearlman** [comment]
I think the question this is trying to answer is "when did they last log 
in" (i.e., when did they last go through whatever login process is used 
by the configured client provider), not "when did they last use our 
service".

                  -- Laura

**Comment by karlcz** [comment]
I am 100% sure that the program managers want to know when people have
stopped using the service.  If we assume sessions are short, these are
reasonably proxies for each other.  But given that there is no upper
limit on session length, I don't think we should conflate the two.  We
could have a login days/weeks/months before the last access if it
never times out.

**Comment by ljpearlman** [comment]
Also #2 could make a user with a currently-open long-running session 
look idle. #1 is probably the way to go. But do we *also* want a 
last-logged-in time?

Since people are already going to need to make some db changes for the 
current set of webauthn updates, I'd like to add the new db columns now, 
so people don't have to update their databases yet again when we 
implement this.

               -- Laura

**Comment by karlcz** [comment]
Yes I think the last login and last access times should both be tracked
for users.

Should we also add a config knob for the update throttling period
(currently hard-coded as 5 seconds I think)?  This should apply
equally to both the session expiry and last-access time updates.

**Comment by ljpearlman** [comment]
I think we should track three things:

1. Last login - the last time the user went through the login process.
2. Last session extension - the last time the user's session was extended.
3. Last group update - the last time the user's groups were verified/updated.

These would all be fields in the user table. Only the client provider would write to that table, but it would provide set_session_extension_time() and set_group_update_time() calls that the session provider would call when it extended a session and the attribute provider would call when it verified a user's groups.

**Comment by hongsudt** [comment]
@ljpearlman Can you schedule time to work on this this month?

**Comment by karlcz** [comment]
I tried to review this and find that the `last_login` `last_session_extension` and `last_group_update` fields of the user table are all NULL on several dev systems that I inspected. @ljpearlman

**Comment by ljpearlman** [comment]
Heh. It turns out I left some files out of the commit. @karlcz

**Comment by karlcz** [comment]
I looked again and at least some production systems are now tracking those webauthn events described as NULL above.  So I'm going to close this very stale review issue...
