### ISSUE TITLE
Error 500 after authenticating with GOAuth

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/webauthn#3]
This was caused by two problems:

1. The goauth attribute provider wasn't creating the attribute tables, causing the attempt to save the user's attributes (groups) to fail.

2. The GOAuth nexus library uses httplib2 to send queries to the GOAuth server. By default, the httplib2 methods check a file in the httplib2 directory to find the list of trusted CAs. The permissions on this file were too restrictive, causing connections to the GOAuth server to fail.

**Comment by bugacov** [comment]
Testing on gpcr-dev.misd.isi.edu I was able to get the goauth to work and was able to create a new catalog in that machine
