### ISSUE TITLE
Always respond with a referer after a logout request, successful or unsuccessful.

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/webauthn#30]

**Comment by karlcz** [comment]
@hongsudt this is something we want reviewed ASAP so I'll put it in current milestone...

**Comment by hongsudt** [comment]
@svoinea can you review and close this feature from @ljpearlman ?

**Comment by svoinea** [comment]
The feature was tested on rbk-dev and works as expected.

The ermrest_config.json file needs to have these two lines:

      "default_logout_path": "/chaise/logout",
      "globus_auth_logout_redirect_name": "RBK"
