### ISSUE TITLE
Add cache to bypass DB for frequent session lookup

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#33]
In micro-benchmarking of the Hatrac object store, the time to obtain the existing session context almost doubles the total request time to find and serve small objects (such as pyramidal image tiles).  It is adding 3-4ms per request.  This has a big impact when doing bulk requests for lots of tiles.

Since there are not that many sessions, I think we can easily cache them in a Python data structure and consider them valid for short periods of time. We should make the time a configurable policy but I think values around 5-30s make sense.  The code should consult this look-aside cache before talking to the DB, and only talk to the DB when the entry in the cache is stale enough to warrant a validity check *or* to do a DB write to extend the session expiration time.

**Comment by karlcz** [comment]
I think this will be handled as part of the new apache module and changing over to use that for hot-path authentication, right @ljpearlman ?

**Comment by ljpearlman** [comment]
Right.

**Comment by karlcz** [comment]
As I understand it, this caching is already implemented and awaits review as part of the overall apache module behavior...

**Comment by karlcz** [comment]
I did a test install of mod_webauthn and confirmed that there is caching of the /authn/session resource, i.e. fewer requests on that resource are logged than the multiple protected resource requests made using a valid session.
