### ISSUE TITLE
Make the Globus group endpoint configurable.

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/webauthn#48]
This was hard-coded into the globus_auth provider. Alejandro needs to change it to test the new facebase branding on the Globus staging site.

**Comment by ljpearlman** [comment]
Added the config parameter `globus_auth_group_endpoint`.

**Comment by karlcz** [comment]
@bugacov has this worked for you?  can we close the issue?

**Comment by karlcz** [comment]
@ljpearlman can you add this parameter and its default value to the sample config and/or documentation?
