### ISSUE TITLE
Specify oauth redirect URLs relative to the host, not the service

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/webauthn#49]
Webauthn expands the oauth2_relative_redirect_uri parameter relative to the current service (e.g., if /authn/session is referenced from within https://myhost/ermrest, it will be expanded to https://myhost/ermrest/authn/session). This isn't what we want with the new /authn service.

**Comment by ljpearlman** [comment]
Added a new parameter, `oauth2_redirect_uri` that does what we want. `oauth2_redirect_relative_uri` is still supported for now.

**Comment by karlcz** [comment]
It seems like I had to edit the oauth secrets "redirect_uris" field as well in order to see callbacks happening on the standalone /authn/session resource.

**Comment by karlcz** [comment]
I did more tests on more VMs and saw this feature working.  Doing controlled tests without any dev-update cron job, editing one config file at a time, and starting from scratch with an empty browser (full restart with cleared cookies and cache), I saw the callback path in ssl_access_log change with the use of `oauth2_redirect_uri` as described by @ljpearlman 

I am not sure how I got the weird symptoms on the first two VMs yesterday, unless I somehow raced with the hourly cron update and saw first the old code and then the new code operating on the same config file settings...
