### ISSUE TITLE
consistent 500 error code for GET /ermrest/authn/session?cid=search

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/webauthn#58]
The search page consistently flashes 500 internal server error before the page is updated properly..  

Here is the link to replicate the issue.. You will need to login first. 
https://data.gpcrconsortium.org/chaise/search/#1/assets:cpm

I looked at the http access log and saw the request with 500.. 
```
128.9.136.150 - https://auth.globus.org/a57909ea-d274-11e5-9c2f-83467f6b5c29 [15/Mar/2017:17:21:50 -0700] "GET /ermrest/catalog/1/schema?cid=search HTTP/2.0" 304 41
128.9.136.150 - https://auth.globus.org/a57909ea-d274-11e5-9c2f-83467f6b5c29 [15/Mar/2017:17:21:51 -0700] "GET /ermrest/authn/session?cid=search HTTP/2.0" 500 47
```

The following errors also showed up in the error log. 
```
[Wed Mar 15 17:36:29.866068 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352] Traceback (most recent call last):
[Wed Mar 15 17:36:29.866120 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]   File "/usr/lib/python2.7/site-packages/web/application.py", line 239, in process
[Wed Mar 15 17:36:29.866130 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]     return self.handle()
[Wed Mar 15 17:36:29.866135 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]   File "/usr/lib/python2.7/site-packages/web/application.py", line 230, in handle
[Wed Mar 15 17:36:29.866141 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]     return self._delegate(fn, self.fvars, args)
[Wed Mar 15 17:36:29.866147 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]   File "/usr/lib/python2.7/site-packages/web/application.py", line 447, in _delegate
[Wed Mar 15 17:36:29.866152 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]     return handle_class(f)
[Wed Mar 15 17:36:29.866157 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]   File "/usr/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
[Wed Mar 15 17:36:29.866162 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]     return tocall(*args)
[Wed Mar 15 17:36:29.866166 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]   File "/usr/lib/python2.7/site-packages/webauthn2/rest.py", line 135, in wrapper
[Wed Mar 15 17:36:29.866171 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]     return original_method(*args)
[Wed Mar 15 17:36:29.866176 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]   File "/usr/lib/python2.7/site-packages/webauthn2/rest.py", line 325, in GET
[Wed Mar 15 17:36:29.866181 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]     preauth_referrer = self.manager.preauth.preauth_referrer()
[Wed Mar 15 17:36:29.866185 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]   File "/usr/lib/python2.7/site-packages/webauthn2/providers/oauth2.py", line 611, in preauth_referrer
[Wed Mar 15 17:36:29.866190 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352]     raise OAuth2ProtocolError("No state argument")
[Wed Mar 15 17:36:29.866195 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352] OAuth2ProtocolError: No state argument
[Wed Mar 15 17:36:29.866227 2017] [wsgi:error] [pid 14890] [remote 128.9.136.150:34352] 
```

**Comment by ljpearlman** [comment]
The API expects GET /session to be called in one of three ways:

1. With no arguments - it returns the current session info
2. With only a "referrer" argument - it also returns the current session info
3. With any other combination of arguments - it assumes the user is logging in and passes those arguments to the handler, which attempts to use them to log in.

In this case, GET /session is being passed the argument "cid=search", so it passes it on to the goauth handler, which assumes the user is trying to log in and complains it's missing a necessary argument ("state").

This should probably be a 4xx error instead of a 5xx error, but then chaise would just flash a different error. Can chaise be changed not to send that argument? If not, I suppose I could add another special case to the session logic.

**Comment by karlcz** [comment]
I think we should special case this and ignore it.  We are using `cid` to try to brand the requests with which particular client app code issued it...

**Comment by svoinea** [comment]
I shall remove the query parameter `cid=search` for the `/ermrest/authn` requests.
So far, I have added that parameter to all the `/ermrest` requests in the `search` application.

**Comment by ljpearlman** [comment]
Okay, I'll special case it (so, thanks Serban, but you can leave search as it is).

**Comment by karlcz** [comment]
I can confirm recent non-500 responses for the GET method on `/authn/session?cid=search` so this is fixed.

(It seems like it may not matter in practice, as this GET message isn't actually one we care to trace... I think we need a more sophisticated bit of tracking if we want to understand the causal linkage to new sessions. Probably the inclusion of a session ID in other events is the best way forward.)
