### ISSUE TITLE
GET preauth should set content-type

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#8]
The preauth response is JSON and so needs `application/json` content-type rather than `text/plain`.

**Comment by karlcz** [comment]
Also, I think this code should be refactored to do the content-negotiation decision between HTML and JSON within the rest.py layer and pass down the decision in the calls to the provider modules. This may mean advertising the supported content types and defaults as provider class members so that the rest wrapper can adapt the negotiation to the types supported by the provider.

**Comment by karlcz** [comment]
@ljpearlman I think this is also done in the globus_auth branch already, right?

**Comment by ljpearlman** [comment]
The version in the branch is currently always returning application/json now (I left a compatibility option to do the content negotiation, but no one is using it). I think we'd agreed to assume that there would always be a GUI layer to consume this kind of information, so I'd like to keep it simple and leave it this way.
